# Copyright 2021 Manna Harbour
# https://github.com/manna-harbour/miryoku

name: 'Build Kyria rev2'
on:
  - workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    with:
      keyboard: '["splitkb/kyria/rev2"]'
